fix: (#27) propriedades vazias tratadas corretamente
Os-Derivados/college-management pull request #28
Opened 2024-12-15 23:59 UTC by xvitxr7

Propriedades vazias agora são tratadas corretamente, com valores nulos convertidos para uma string vazia, evitando uma ``NullReferenceException``.

2024-12-18 00:28 UTC, trsaints reviewed
Realmente existe essa possibilidade? Ou é só uma checagem arbitrária da IDE.

2024-12-18 00:43 UTC, trsaints requested changes
Conforme o exemplo abaixo, o sistema está permitindo registrar instâncias de `Usuario` sem credenciais. Isso não deve acontecer em hipótese alguma:

```json
	{
		"$type": "aluno",
		"MatriculaId": "10000000001",
		"Login": "",
		"Nome": "",
		"CargoId": "10000000001",
		"Credenciais": {
			"Senha": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			"Sal": "5C969B17E42A10AC29C4ECAF"
		},
		"Id": "10000000002"
	}
```

O tratamento mais efetivo é não permitir a inserção de valores nulos para essas informações principais.

2024-12-18 02:37 UTC, xvitxr7 commented
> Conforme o exemplo abaixo, o sistema está permitindo registrar instâncias de `Usuario` sem credenciais. Isso não deve acontecer em hipótese alguma:
> 
> ```json
> 	{
> 		"$type": "aluno",
> 		"MatriculaId": "10000000001",
> 		"Login": "",
> 		"Nome": "",
> 		"CargoId": "10000000001",
> 		"Credenciais": {
> 			"Senha": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
> 			"Sal": "5C969B17E42A10AC29C4ECAF"
> 		},
> 		"Id": "10000000002"
> 	}
> ```
> 
> O tratamento mais efetivo é não permitir a inserção de valores nulos para essas informações principais.

Então o tratamento adequado seria impedir credencias vazias no cadastro e avisar caso exista um usuário considerado inválido na base de dados e talvez tomar as devidas providências, certo?

2024-12-18 03:12 UTC, xvitxr7 commented
E outra, isso não acontece só com usuários. Qualquer modelos com propriedades vazias está suscetível à esse probleminha. Por exemplo: Cursos sem alunos, cargos sem usuários e etc.

2024-12-18 03:13 UTC, xvitxr7 commented
> Realmente existe essa possibilidade? Ou é só uma checagem arbitrária da IDE.

Do que você está se referindo?

2024-12-18 22:48 UTC, trsaints commented
> > Realmente existe essa possibilidade? Ou é só uma checagem arbitrária da IDE.
> 
> Do que você está se referindo?

Isso realmente está causando alguma Exception em algum momento? Vale lembrar que esses null checks e avisos sobre valores nulos são a nível de compilação, e não de execução

2024-12-19 00:33 UTC, xvitxr7 commented
> > > Realmente existe essa possibilidade? Ou é só uma checagem arbitrária da IDE.
> > 
> > 
> > Do que você está se referindo?
> 
> Isso realmente está causando alguma Exception em algum momento? Vale lembrar que esses null checks e avisos sobre valores nulos são a nível de compilação, e não de execução

Sim, nos meus testes, o programa jogava uma ``NullReferenceException`` bem nessa parte, no commit. Claro que isso foi num contexto específico, então pode ser que o _problema_ não seja necessariamente um bug.
Minha opinião é que isso é um bug, mas estarei aguardando novas instruções e perspectivas da situação.

2024-12-20 02:15 UTC, trsaints commented
> > Conforme o exemplo abaixo, o sistema está permitindo registrar instâncias de `Usuario` sem credenciais. Isso não deve acontecer em hipótese alguma:
> > ```json
> > 	{
> > 		"$type": "aluno",
> > 		"MatriculaId": "10000000001",
> > 		"Login": "",
> > 		"Nome": "",
> > 		"CargoId": "10000000001",
> > 		"Credenciais": {
> > 			"Senha": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
> > 			"Sal": "5C969B17E42A10AC29C4ECAF"
> > 		},
> > 		"Id": "10000000002"
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > O tratamento mais efetivo é não permitir a inserção de valores nulos para essas informações principais.
> 
> Então o tratamento adequado seria impedir credenciais vazias no cadastro e avisar caso exista um usuário considerado inválido na base de dados e talvez tomar as devidas providências, certo?

Sim. Precisamos evitar que o usuário registre campos nulos. A princípio.

2024-12-20 02:16 UTC, trsaints approved these changes
Estarei aprovando este ajuste, pois iremos trabalhar na validação visual posteriormente.

2024-12-20 02:18 UTC, merged