[ContextoCursos](#15) Implementado VerGradeCurricular, Visualizar e VerDetalhes
Os-Derivados/college-management pull request #39
Opened 2024-12-18 03:27 UTC by xvitxr7

Como descrito no título, os recursos ``VerGradeCurricular``, ``Visualizar`` e ``VerDetalhes`` foram implementados e aparentam estar funcionando corretamente nos meus testes.

Adendo: No recurso ``VerDetalhes``, talvez um erro aconteça ao tentar ver detalhes de um curso sem alunos matriculados devido à #27.

2024-12-18 20:06 UTC, xvitxr7 commented
Transformado num rascunho visto que as implementações não estão totalmente completas.

2024-12-18 22:51 UTC, trsaints reviewed
Preciso que entre em contato com o @CharlesSanto, para ver se ele não estava trabalhando nesta task localmente. Ele me informou que estaria trabalhando nessas funcionalidades, antes de abrirmos o grupo.

2024-12-22 01:04 UTC, xvitxr7 commented
Não poderei confirmar review por enquanto por conta de @CharlesSanto, que supostamente também está trabalhando no caso, não poder acessar seu computador no momento.

2025-01-07 10:42 UTC, trsaints requested changes
Alguns ajustes precisam ser realizados.

2025-01-07 15:50 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +    private Curso PesquisarCurso()
Eu também notei essa recorrência, porém não tinha certeza se a criação de uma nova View inteira fosse mesmo necessária.

2025-01-07 19:56 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +        var nomesPropriedadesRaw = propriedades.Select(i => i.Name);
Por conta de tantas mudanças que eu fiz, acabei esquecendo dessa porção. Resolvido. [#5cc78aa](https://github.com/Os-Derivados/college-management/pull/39/commits/5cc78aaafe2616f07c3490de8e3d1d8e15e46c3d)

2025-01-07 19:58 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +            return operacao();
Possivelmente tratado em [#5cc78aa](https://github.com/Os-Derivados/college-management/pull/39/commits/5cc78aaafe2616f07c3490de8e3d1d8e15e46c3d).

2025-01-07 19:58 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +            Aluno? aluno = UsuarioContexto as Aluno ?? throw new InvalidOperationException("O usuário atual não é um aluno.");
Possivelmente tratado em [#5cc78aa](https://github.com/Os-Derivados/college-management/pull/39/commits/5cc78aaafe2616f07c3490de8e3d1d8e15e46c3d).

2025-01-07 19:58 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +                .FirstOrDefault() ?? throw new InvalidOperationException("O atual usuário não está matriculado em nenhum curso.");
Possivelmente tratado em [#5cc78aa](https://github.com/Os-Derivados/college-management/pull/39/commits/5cc78aaafe2616f07c3490de8e3d1d8e15e46c3d).

2025-01-07 20:00 UTC, xvitxr7 commented on college-management/Contextos/ContextoCursos.cs
> +                .FirstOrDefault() ?? throw new InvalidOperationException("O atual usuário não está matriculado em nenhum curso.");
Possivelmente tratado em [#5cc78aa](https://github.com/Os-Derivados/college-management/pull/39/commits/5cc78aaafe2616f07c3490de8e3d1d8e15e46c3d).

2025-01-09 00:14 UTC, trsaints approved these changes

2025-01-09 00:15 UTC, merged