[ContextoCursos](#16) Implementado  Visualizar, VerDetalhes, Cadastrar ,Excluir e Editar
Os-Derivados/college-management pull request #46
Opened 2024-12-21 03:16 UTC by CsPauloNoob

Além do exposto acima, todas as funções foram testadas.

2024-12-21 07:14 UTC, xvitxr7 commented
Acho que você errou o nome, era pra ser "ContextoCargos", né?

2024-12-21 18:25 UTC, CsPauloNoob commented
verdade, corrigido.

2024-12-22 01:37 UTC, xvitxr7 requested changes
Estou fazendo essa review sem considerar qualidade de código, apenas funcionalidade.

### Observações:

- No recurso Detalhes, a view usada é a ``RelatorioView`` invés da apropriada ``DetalhesView``.

- Eu não vi salvaguardas quanto a exceções no código. A maioria se não todos os simples erros como IDs ou Nomes não encontrados na base de dados, jogam exceções e terminam a aplicação, sendo uma grande incoveniência. Diria até que é uma mudança importante a se fazer.

- No recurso Visualizar, podemos ver que algumas informações estão erradas, como ``Id`` estar no lugar de ``UsuariosId``, mas entendo que isso já é um problema fora do escopo da issue.

- No recurso Editar, não é possível escolher mais de uma permissão para o cargo, mas entendo as complexidades de tal função, então não estou considerando como importante.

- No recurso Cadastrar e Editar, é possível cadastrar  e editar cargos com nomes vazios ("").

- ~~A branch não está em dia com ``main``.~~

De mais, as funcionalidades funcionam como deveriam, na maioria das vezes.

2024-12-27 00:06 UTC, trsaints commented
> Estou fazendo essa review sem considerar qualidade de código, apenas funcionalidade.
> 
> ### Observações:
> * No recurso Detalhes, a view usada é a `RelatorioView` invés da apropriada `DetalhesView`.
> * Eu não vi salvaguardas quanto a exceções no código. A maioria se não todos os simples erros como IDs ou Nomes não encontrados na base de dados, jogam exceções e terminam a aplicação, sendo uma grande incoveniência. Diria até que é uma mudança importante a se fazer.
> * No recurso Visualizar, podemos ver que algumas informações estão erradas, como `Id` estar no lugar de `UsuariosId`, mas entendo que isso já é um problema fora do escopo da issue.
> * No recurso Editar, não é possível escolher mais de uma permissão para o cargo, mas entendo as complexidades de tal função, então não estou considerando como importante.
> * No recurso Cadastrar e Editar, é possível cadastrar  e editar cargos com nomes vazios ("").
> * ~A branch não está em dia com `main`.~
> 
> De mais, as funcionalidades funcionam como deveriam, na maioria das vezes.

Acredito que a ordem as chaves primária e estrangeira deva ser consequência do método `ToString` do objeto `Cargo`. Não acho que uma correção fuja do escopo.

2024-12-27 00:09 UTC, trsaints commented on college-management/Contextos/ContextoCargos.cs
> +	public override async Task Excluir()
Ao tentar excluir um `Cargo` inexistente, o sistema lança um `NullReferenceException`.

2024-12-27 00:10 UTC, trsaints requested changes
Alguns comportamentos inesperados acontecem com a inserção de informações "inválidas" (na natureza do programa em si, mas não necessariamente da lógica de negócios).

2024-12-27 00:10 UTC, trsaints commented on college-management/Contextos/ContextoCargos.cs
> +	public override async Task Excluir()
O programa dá crash ao tentar excluir um cargo inexistente.

2025-01-07 10:58 UTC, trsaints requested changes
Ao selecionar uma permissão a ser associada ao `Cargo`, o programa não segue a execução, exigindo pressionar a tecla `[Enter]` para continuar.

2025-01-09 03:32 UTC, CsPauloNoob commented
@xvitxr7 dei fix no código de acordo com as suas observações, com exceção de:

> No recurso Visualizar, podemos ver que algumas informações estão erradas, como Id estar no lugar de UsuariosId, mas entendo que isso já é um problema fora do escopo da issue.

Que será tratado em uma issue futura.


@trsaints Acredito que resolvi o problema que um Console.ReadKey estava causando, fazendo ser necessário pressionar o Enter para pular uma tela em branco, após a parte  de seleção de permissão na função de cadastrar.

2025-01-13 02:09 UTC, CsPauloNoob commented
reabri o PR, mas ainda não corrigi algumas coisas solicitadas

2025-01-13 23:33 UTC, xvitxr7 requested changes
Tudo parecer estar funcionando corretamente desta vez, meus testes não revelaram problemas nem bugs que quebram o software.
Única coisa estranha que percebi foi que o cargo ``Alunos`` não tem o usuário teste, mesmo ele tendo o cargo ``Alunos``.

2025-01-13 23:33 UTC, xvitxr7 commented on college-management/Contextos/ContextoCargos.cs
> +    }
A forma na qual esse método foi implementado faz edições diretamente no cargo, e como ``Cargo`` é uma classe ([*reference type*](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types)), ``cargoAtual`` é uma direta referência ao cargo alvo a ser editado. Isso significa que edições são feitas antes mesmo do usuário autorizá-las.
```suggestion
    // Marcar como nullable é sempre boa prática para melhor leitura de código e para evitar bugs.
    Cargo? TelaDeEdicao(Cargo cargoAtual, InputView inputView)
    {
        inputView.LerEntrada("nome",
            $"Nome Atual: {cargoAtual.Nome}\n\nEscolha um novo nome: ");

        if (ValidaEntrada(inputView, "nome"))
        {
            List<string> permissoes = SelecaoDePermissao();
            if (!permissoes.Any()) return null;
            
            return new Cargo(inputView.ObterEntrada("nome"), permissoes); // Retorna um novo cargo invés de usar o existente.
        }

    return null;
}
```

2025-01-14 00:39 UTC, trsaints commented
sua branch teve um pequeno conflito e precisei realizar as devidas alterações.

2025-01-14 02:43 UTC, CsPauloNoob commented on college-management/Contextos/ContextoCargos.cs
> +    }
> Única coisa estranha que percebi foi que o cargo Alunos não tem o usuário teste, mesmo ele tendo o cargo Alunos.

Acredito que isso seja problema na hora de seedar o "banco"


> A forma na qual esse método foi implementado faz edições diretamente no cargo, e como Cargo é uma classe ([reference type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types)), cargoAtual é uma direta referência ao cargo alvo a ser editado. Isso significa que edições são feitas antes mesmo do usuário autorizá-las.

Sim, eu acabei esquecendo desse erro que identifiquei faz bastante tempo. Valeu pela resposta implemente ela no commit [1060205](https://github.com/Os-Derivados/college-management/pull/46/commits/106020521eb28a0e2ef600a149c6342db79820fa) com uma pequena alteração.

2025-01-14 02:44 UTC, xvitxr7 approved these changes

2025-01-21 01:45 UTC, trsaints requested changes
Uma correção pontual deve ser feita para que o fluxo de interação fique mais intuitivo e explícito.

2025-01-21 01:45 UTC, trsaints commented on college-management/Contextos/ContextoCargos.cs
> +	public override async Task Excluir()
O programa exclui o `Cargo` sem nenhuma confirmação prévia.
Também só permite a busca por `Nome`, quebrando o padrão estabelecido para busca de registros em outros `Contexto`s.

2025-01-21 02:33 UTC, CsPauloNoob commented on college-management/Contextos/ContextoCargos.cs
> +	public override async Task Excluir()
Tela de confirmação adicionada no último commit

2025-01-22 02:26 UTC, CsPauloNoob commented on college-management/Contextos/ContextoCargos.cs
> +	public override async Task Excluir()
adicionei a feature de pesquisa por id e nome em excluir.

2025-01-22 03:10 UTC, trsaints approved these changes
Algumas redundâncias estão perdurando em todos os `Contexto`s, indicando a possível necessidade da implementação de novos serviços.

Os métodos principais estão funcionando adequadamente.

2025-01-22 03:10 UTC, merged